### PR TITLE
Introduces a refunds endpoint supporting the credit transfers feed

### PR DESCRIPTION
**Pull request by rvvincelli**
Hi @koen-serry ,

I am not 100% sure the [credit transfer feed](https://www.twikey.com/api/index.html#refunds-credit-transfer) behaves exactly like the other feeds you've implemented already, the 'feed' word makes me think so. We'd like the very same callback approach though, to keep it consistent. By looking at the example, this endpoint just returns updates with no defined state.

Thanks!

### CODE REVIEW

**Review by abojic — COMMENTED** [review]
Hi @rvvincelli ,
Thank You for your contribution. We've rearranged structure of the project so can you please align your changes with the new structure. 
Also, there is no need for a constructor inside the RefundGateway class anymore.

Thanks.

Alan

**Comment by koen-serry** [comment]
Hi @rvvincelli, yesterday @abojic renamed the unfortunately named "Helper" package to "Callback" which was indeed a better name as well as the strict_type hint for extra safety. Would you be able to modify your gateway?

**Comment by rvvincelli** [comment]
Hi guys! Yes I should be able, let me have a look.

**Comment by rvvincelli** [comment]
Done, but Github is bellyup today, ~~I'll push tomorrow~~, pushed, thanks,

**Comment by rvvincelli** [comment]
@koen-serry @abojic please let me know when you update the package upstream so we can leave the local patches behind, thanks,

**Comment by rvvincelli** [comment]
@koen-serry @abojic thanks for merging! I'll just update the Composer ref to point to `dev-master` so to get all of our latest changes. Thanks,

**Pull request merged**
